version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(ci):"
  # Python uv
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(backend):"
  # npm
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(frontend):"
    ignore:
      - dependency-name: "@hey-api/openapi-ts"
  # Docker
  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(tools/docker):"
  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(tools/docker):"
